metrics_resource = {
    "Gls": "Goals scored or allowed.",
    "Ast": "Assists.",
    "G+A": "Combined total of goals and assists.",
    "G-PK": "Goals excluding penalties.",
    "PKatt": "Penalty kicks attempted.",
    "xG": "Expected Goals (xG) estimates how likely a shot is to become a goal based on similar past chances — distance, angle, body part, etc.",
    "xAG": "Expected Assists (xA) measures the likelihood that a pass becomes a goal — even if it didn’t result in one.",
    "npxG": "Non-penalty Expected Goals. xG minus penalty xG.",
    "npxG+xAG": "Sum of Non-penalty Expected Goals and Expected Assists.",
    "PrgC": "Progressive Carries — carries that move the ball significantly closer to goal. Shows line-breaking dribbles and runs.",
    "PrgP": "Progressive Passes — forward passes that advance play meaningfully.",
    "PrgR": "Progressive Passes Received — when a player receives a forward pass in an advanced area.",
    "G+A-PK": "Non-penalty Goals + Assists.",
    "xG+xAG": "Sum of Expected Goals and Expected Assists.",
    "Touches": "Total touches by the player.",
    "Def Pen": "Touches in the defensive penalty area.",
    "Def 3rd": "Touches in defensive third of the pitch.",
    "Mid 3rd": "Touches in the middle third.",
    "Att 3rd": "Touches in the attacking third.",
    "Att Pen": "Touches inside the opponent's penalty box.",
    "Live": "Touches during live play (not from set pieces).",
    "Succ": "Successful dribbles.",
    "Succ%": "Percentage of successful take-ons.",
    "Tkld": "Times tackled while dribbling.",
    "Tkld%": "Percentage of take-ons where the player was tackled.",
    "Carries": "Number of times a player controls and moves with the ball.",
    "TotDist": "Total distance carried with the ball in meters.",
    "PrgDist": "Distance of progressive carries — forward carries only.",
    "1/3": "Carries into the final third.",
    "CPA": "Carries into the penalty area.",
    "Mis": "Miscontrols that result in loss of possession.",
    "Dis": "Times dispossessed by an opponent.",
    "Rec": "Passes received by the player.",
    "SCA": "Shot-Creating Actions — two offensive actions leading to a shot.",
    "SCA90": "SCA normalized per 90 minutes.",
    "PassLive": "Passes made during live play.",
    "PassDead": "Passes from dead-ball situations (corners, free kicks).",
    "GCA": "Goal-Creating Actions — offensive actions that directly lead to a goal.",
    "GCA90": "GCA per 90 minutes.",
    "Cmp": """Total Passes completed""",
    "KP": """Key Passes that lead to a shot."""
}
