from langgraph.graph import MessagesState
from pydantic import BaseModel
from typing import Annotated, Optional, TypedDict, List

class Done(BaseModel):
    """Return this if no tool_call is needed anymore."""
    done: Annotated[str, "Done message will be used to terminate the workflow"]

class OrchestrationState(TypedDict):
    """
    Track the state of the orchestrator in handling tool_response, observation and tool_choice_reasoning
    """
    tool_call_request: Annotated[Optional[str], "Request to make a tool_calling decision to the tool_calling agent."]
    reasoning: Annotated[str, "Reason why to choose that tool."]

class CurrentState(MessagesState):
    """Tracks the state of the Football Analyst Agentic System across steps.
    Includes user query and intermediate file paths generated by the data analyst, 
    database manager, and visualization components.
    """
    prev_tool_call_request: Annotated[str, "Tool Call Order."]
    prev_tool_reasoning: Annotated[str, "Reason why you choose the tool."]
    prev_tool_result: Annotated[str, "Results from tool call."]
    prev_tool_name: Annotated[str, "Tool name"]
    insights: Annotated[List[str], "Insights so far up until the current step."]